require_relative "../app/models/exercise"
require_relative "../app/models/routine"


Exercise.destroy_all
#exercises
Exercise.create(name:"Muscle-up", difficulty:"hard", reps:"", description:"One of the hardest exercises you can do on a bar.  It's a pull up immediately followed by a dip and requires an explosive movement to make it up. Takes months of prep, start with the dips first, then the pull up then when you can manage 20 pull and 20 pull ups, try the muscle-up ",youtube_url:"", image_url:"/images/muscle_up.jpg")
Exercise.create(name:"Clap pull ups", difficulty:"medium/hard", reps:"", description:"Is an explosive pull-up where you clap inbetween reps.  Requires a lot of momentum and will take a while to get the strength.  Try performing a pull up and tring to spring you hands of the bar as opposed to a clap to get the the explosive movement right, then incoporate the clap",youtube_url:"", image_url:"/images/clap_pull_up.jpg")
Exercise.create(name:"Typewriter pull up", difficulty:"hard", reps:"", description:"Assume a a pull-up position with a wide grip.  Lift you chin abover the bar and begin to straighten one of your arms and durect you body away from the straight arm.  Repeat the process in an opposite direction",youtube_url:"", image_url:"/images/typewriter_pull_up.jpg")
Exercise.create(name:"Standard pull-up", difficulty:"easy", reps:"", description:"Wrap you're hands around the bar and lift your self towards the ceiling until you chin is purched over the bar and then allow you body to come back down",youtube_url:"", image_url:"/images/pull_up.jpg")
Exercise.create(name:"close grip pull up", difficulty:"easy", reps:"", description:"Exactly the same as the regular pull up except your hands are very close together.  This exercise should be performed with a reversed grip", youtube_url:"", image_url:"/images/close_grip_pull_up.jpg")
Exercise.create(name:"Typewriter press up", difficulty:"hard", reps:"", description:"Assume a pressup position and then place your arms in a wide stance.  Lower your body to one side, then slide your body over to the other hand. Make sure you keep your body slightly above floor level, pushing up. When you come back down, slide your body to the right and push up.",youtube_url:"", image_url:"/images/typewriter_press_up.jpg")
Exercise.create(name:"Diamond Pushup", difficulty:"medium", reps:"", description:"A diamond push-up involves keeping your hands close enough to touch the tips of your index fingers and thumbs to each other, making a diamond-like shape then perform a push up",youtube_url:"", image_url:"/images/diamond_press_up.jpg")
Exercise.create(name:"Dip", difficulty:"medium", reps:"", description:"Breathe at The Top. Balance yourself on the dip bars with locked elbows and your feet in the air. Raise your chest to keep your shoulders down. Then take a big breath, hold it and dip down.",youtube_url:"", image_url:"/images/dip.jpg")
Exercise.create(name:"Superman pushup", difficulty:"hard", reps:"", description:"Start in the up position, as you would a normal push-up. But after you come down, explode upward and throw your hands out forward, as though you are Superman flying through the air. If you can, pull up your back legs as well, so that your body is completely airborne and parallel with the ground.",youtube_url:"", image_url:"/images/superman.jpg")
Exercise.create(name:"Spiderman pushup", difficulty:"medium", reps:"", description:"Push yourself back up to the plank position. Repeat the same movement, but this time bring your left knee forward to your left elbow. Continue alternating sides for as many reps as you want. The advantages of doing a Spiderman pushup are that it helps your chest and arm muscles work harder.",youtube_url:"", image_url:"/images/spiderman.jpg")
Exercise.create(name:"Jump Squat", difficulty:"easy", reps:"", description:"Stand with your feet shoulder-width apart. Start by doing a regular squat, then engage your core and jump up explosively. When you land, lower your body back into the squat position to complete one rep. Land as quietly as possible, which requires control.",youtube_url:"", image_url:"/images/jump_squat.jpg")
Exercise.create(name:"Jump lunge", difficulty:"easy", reps:"", description:"Begin in a lunge position. Jump up and quickly swap leg positions in mid-air, whilst keeping your torso straight. Raise your hands to gain height. Land in the lunge position bending your knees to absorb the impact. Launch straight into the next jump switching your feet once more and landing in your original lunge position.",youtube_url:"", image_url:"/images/lunge.jpg")
Exercise.create(name:"Jumps", difficulty:"easy-hard", reps:"", description:"Find a platform on which you can jump safely off both feet, and land both feet on the platform. Alter the height of the platform to increase or decrease difficulty",youtube_url:"", image_url:"/images/jumps.jpg")
Exercise.create(name:"Burpees", difficulty:"easy", reps:"", description:"Stand with your feet hip width apart and your arms down by your side. Lower into a squat position with your hands flat on the floor in front of you. Kick your legs backwards into a press up position and lower your chest to the floor. Push your chest back up to the press up position thrust both feet forward so you are back in the squat position. Jump up and raise both hands over your head",youtube_url:"", image_url:"/images/burpees.jpg")
Exercise.create(name:"Wall sit", difficulty:"easy", reps:"", description:"Wall squats (also called wall sits) are the perfect exercise to strengthen your upper legs. Stand with your back against a wall, placing your feet about two feet out in front of you. Feet should be hip-distance apart. Bending your knees, slide your back down the wall until your knees are at 90 degree angles",youtube_url:"", image_url:"/images/wall_sit.jpg")
Exercise.create(name:"Front leaver", difficulty:"hard", reps:"", description:"The front lever is rarely achieved without appropriate strength and gymnastics training. See the progression exercises section below to learn how to build up to the hold. Assume an inverted hang position on a pull-up bar or gym rings. Lower the body slowly down until completely horizontal (your body facing upwards).",youtube_url:"", image_url:"/images/front_leaver.jpg")
Exercise.create(name:"Back leaver", difficulty:"hard", reps:"", description:"The back lever builds upper body strength and teaches the important skills of total body tension and coordination. First, you'll grab the bar (or rings), get into a tuck, and invert yourself. Simple enough. Continue bringing your feet over your head until you can get in the position shown above.",youtube_url:"", image_url:"/images/back_leaver.jpg")
Exercise.create(name:"Planche", difficulty:"hard", reps:"", description:"Start in a tuck planche, then move your knees back until they are floating in an open tuck planche. From the tuck planche, push one leg back into a single leg planche. From the tuck, straighten the legs into a full straddle planche. You can work on these with a pause, a longer hold, and/or repeats for conditioning.",youtube_url:"", image_url:"/images/planche.jpg")
Exercise.create(name:"Plank", difficulty:"easy", reps:"", description:"Start by getting into a press up position. Bend your elbows and rest your weight ono your forearms and not on your hands. Your body should form a straight line from shoulders to ankles. Engage your core by sucking your belly button into your spine. Hold this position for the prescribed time.",youtube_url:"", image_url:"/images/plank.jpg")
Exercise.create(name:"Hanging leg raise", difficulty:"medium", reps:"", description:"Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. Raise your legs until the torso makes a 90-degree angle with the legs.Go back slowly to the starting position as you breathe in.",youtube_url:"", image_url:"/images/hanging.jpg")