require_relative "../app/models/exercise"
#exercises
Exercise.create(name:"Muscle-up", difficulty:"hard", reps:"", description:"One of the hardest exercises you can do on a bar.  It's a pull up immediately followed by a dip and requires an explosive movement to make it up. Takes months of prep, start with the dips first, then the pull up then when you can manage 20 pull and 20 pull ups, try the muscle-up ",youtube_url:"", image_url:"/public/images/Pullup.png")
Exercise.create(name:"Clap pull-ups", difficulty:"medium/hard", reps:"", description:"Is an explosive pull-up where you clap inbetween reps.  Requires a lot of momentum and will take a while to get the strength.  Try performing a pull up and tring to spring you hands of the bar as opposed to a clap to get the the explosive movement right, then incoporate the clap",youtube_url:"", image_url:"/public/images/Pullup.png")
Exercise.create(name:"Typewriter", difficulty:"Hard", reps:"", description:"Assume a a pull-up position with a wide grip.  Lift you chin abover the bar and begin to straighten one of your arms and durect you body away from the straight arm.  Repeat the process in an opposite direction",youtube_url:"", image_url:"/public/images/Pullup.png")
Exercise.create(name:"Standard pull-up", difficulty:"easy", reps:"", description:"Wrap you're hands around the bar and lift your self towards the ceiling until you chin is purched over the bar and then allow you body to come back down",youtube_url:"", image_url:"/public/images/Pullup.png")
Exercise.create(name:"close grip pull-up", difficulty:"easy", reps:"", description:"Exactly the same as the regular pull up except your hands are very close together.  This exercise should be performed with a reversed grip", youtube_url:"", image_url:"/public/images/Pullup.png")

Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")
Exercise.create(name:"", difficulty:"", reps:"", description:"",youtube_url:"", image_url:"")